use_frameworks!

platform :ios, '8.0'

target 'SJPageViewController_Example' do
  pod 'SJPageViewController', :path => '../'

  target 'SJPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
